### ISSUE TITLE
Wrong Base at Maust

### ISSUE THREAD

**Issue by kcphysics** [roblevesque/webglmapview#3]
This morning, it looks like Flagrante Bello is in the wrong spot.  Should be at Gornor, listed near Maust in the DQ.

**Comment by kcphysics** [comment]
![image](https://user-images.githubusercontent.com/3819657/86357568-08356c80-bc3c-11ea-931f-dbd562a024eb.png)

**Comment by roblevesque** [comment]
Thanks for the heads up. Appears that It was also listed as Romulan too. This data was pulled directly from the MUSHClient plugin. Since that plugin data lacks that base I think I'm going to pull it for now until I can get the appropriate coordinates from in game.
